connectors:
 - {configuration: can.json, name: can, type: can}
storage:
#  type: memory
#  read_records_count: 100
#  max_records_count: 100000
  data_folder_path: ./data/
  max_file_count: 100
  max_read_records_count: 100
  max_records_per_file: 10000
  type: file
wthings:
  host: things.xiaobodata.com
  port: 1883
  remoteConfiguration: false
  security:
    accessToken: NEumqP7X2nucimbjamUZ
